# Generated by Django 5.2 on 2025-04-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_testimonial_options_alter_testimonial_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-rating', '-created_at'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
